<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_JetTheme
 */
?>
<?php
/**
 * @var $block Magento\Catalog\Block\Product\AbstractProduct
 * @var $amProductCaretViewModel Amasty\JetTheme\ViewModel\ProductCaret\ProductCaretConfigurationViewModel
 * @var $escaper Magento\Framework\Escaper
 * @var \Ecommage\BookingViewProduct\Helper\Data $helper
 */
$helper = $this->helper('Ecommage\CustomCatalog\Helper\Data');// @codingStandardsIgnoreLine
// phpcs:disable
$brandHelper = $this->helper(\Amasty\ShopbyBase\Helper\OptionSetting::class);
$catalogHelper = $this->helper(\Ecommage\CustomCatalog\Helper\Data::class);
$storeID       = $catalogHelper->getStoreId();
// phpcs:enable
$amProductCaretViewModel = $block->getAmProductCaretViewModel();
$isProductCaretEnabled = $amProductCaretViewModel ? $amProductCaretViewModel->isProductCaretEnabled() : null;
$isProductSliderEnabled = false;
$product = $helper->getModelProduct();
switch ($type = $block->getType()) {
    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;
            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;
            $image = 'related_products_list';
            $title = __('View more products in collection');
            $items = $block->getItems();
            $limit = 4;
            $shuffle = 0;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;
            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;
            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;
            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;
            $image = 'cart_cross_sell_products';
            $title = __('A few recommendations');
            $items = $block->getItems();
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
        break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;
            $class = 'widget' . ' ' . $type;
            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
        break;

    default:
        $exist = null;
}
?>

<?php if ($exist): ?>
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= $escaper->escapeHtmlAttr($class) ?>"
                 data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'
                 data-limit="<?= $escaper->escapeHtmlAttr($limit) ?>"
                 data-shuffle="<?= /* @noEscape */ $shuffle ?>">
        <?php else: ?>
            <div class="block <?= $escaper->escapeHtmlAttr($class) ?>"
                 data-mage-init='{"upsellProducts":{}}'
                 data-limit="<?= $escaper->escapeHtmlAttr($limit) ?>"
                 data-shuffle="<?= /* @noEscape */ $shuffle ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= $escaper->escapeHtmlAttr($class) ?>">
    <?php endif; ?>
            <div class="block-title title title__wrapper"
                 id="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading"
                 role="heading"
                 title="<?= $escaper->escapeHtmlAttr($title) ?>"
                 aria-level="2">
                 <span class="text_line">
                     <?= $escaper->escapeHtml($title) ?>
                 </span>
            </div>
            <div class="block-content content" aria-labelledby="block-<?= $escaper->escapeHtmlAttr($class) ?>-heading">
                <div class="products wrapper grid products-grid products-<?= $escaper->escapeHtmlAttr($type) ?>">
                    <ol class="products list items product-items amtheme-products-secondary <?= $isProductSliderEnabled ? ' amtheme-slick-slider' : '' ?>"
                        <?php if ($isProductSliderEnabled): ?>
                            data-mage-init='{"slickSlider": {
                                "isOnMobile": false,
                                "sliderOptions": {
                                <?php if ($isProductCaretEnabled && $isProductCaretEnabled === 'sidebar'): ?>
                                    "slidesToShow": 4,
                                <?php else: ?>
                                    "slidesToShow": 4,
                                    "responsive": [
                                        {
                                            "breakpoint": 1280,
                                            "settings": {
                                                "slidesToShow": 4
                                            }
                                        },
                                        {
                                            "breakpoint": 1023,
                                            "settings": {
                                                "slidesToShow": 4
                                            }
                                        }
                                    ],
                                <?php endif; ?>
                                    "dots": false
                                }
                            }}'
                            <?php endif; ?>
                        >
                        <?php foreach ($items as $item): ?>
                            <?php  $available = ''; ?>
                            <?php if (!$item->isComposite() && $item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$item->getRequiredOptions()): ?>
                                    <?php $available = 'related-available'; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php if ($type == 'related' || $type == 'upsell'): ?>
                                <li class="item product product-item" style="display: none;">
                            <?php else: ?>
                                <li class="item product product-item">
                            <?php endif; ?>
                            <div class="product-item-info <?= /* @noEscape */ $available ?>">
                                <a href="<?= $escaper->escapeUrl($block->getProductUrl($item)) ?>"
                                   title="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                   class="product photo product-item-photo">
                                    <?= $block->getImage($item, $image)->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <span class="product name product-item-name">
                                        <a class="product-item-link"
                                           title="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                           href="<?= $escaper->escapeUrl($block->getProductUrl($item)) ?>">
                                            <?= $escaper->escapeHtml($item->getName()) ?>
                                        </a>
                                    </span>
                                    <?php if ($type == 'crosssell' || $type == 'upsell'): ?>
                                        <div class="product-details-sku-brand">
                                            <span class="product-details-sku">
                                                <?= $escaper->escapeHtml($item->getSku()) ?>
                                            </span>
                                        </div>
                                        <?php
                                            if($item->getTypeId() == 'simple'){
                                                $item = $product->load($item->getId());
                                            }
                                            $qtyAndStock = $helper->checkQtyAndStockOptionProduct($item);
                                        ?>
                                        <?php if(!$qtyAndStock || !$item->isSalable()): ?>
                                            <div class="product-contact">
                                                <?= $block->escapeHtml(__('Contact Price')); ?>
                                            </div>
                                        <?php else: ?>
                                            <?= /* @noEscape */ $block->getProductPrice($item) ?>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            </li>
                        <?php endforeach ?>
                    </ol>
                    <?php  if ($type == 'crosssell'): ?>

                        <div class="button-link">
                            <a href="<?= $block->escapeUrl($helper->getRandomUrlCategory()); ?>" class="pagebuilder-button-link">
                                <span><?= $block->escapeUrl(__('View all product')); ?></span>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
<?php endif;?>
