<?php
/** @var \Ecommage\BannerManager\Model\Banner\Item $item */

/** @var \Ecommage\BannerManager\Block\Banner $block */
$banner = $block->getBanner();

if ($banner && $banner->getId() && $banner->getTypeId() == 2):
    $items     = $block->getBannerItems();
    $elementId = $block->getElementId();
    $options   = $banner->getOptions();
    $optionJson = str_replace('"', '', json_encode($options));
    $width     = $options['width'] ?? 500;
    $height    = $options['height'] ?? 300;
    ?>
    <div id="<?= $block->escapeHtmlAttr($elementId) ?>" class="banner-image">
        <div class="sp-images widget-video">
            <?php foreach ($items as $item): ?>
                <div class="sp-image banner-item-<?= /** @noEscape  */ $item->getId(); ?>">
                    <?php if ($block->isVideo($item)): ?>
                        <?php if($block->getVideoYoutube($item)): ?>
                            <div class="sp-static" data-horizontal="30" data-vertical="30">
                                <div class="sp-video">
                                    <?= /* @noEscape */ $block->getVideoYoutube($item); ?>
                                </div>
                            </div>
                        <?php else:?>
                            <div class="sp-static" data-horizontal="30" data-vertical="30">
                               <div class="sp-video">
                                    <video style="object-fit: cover;" width="<?=  $block->escapeHtml($width) ?>" height="<?= $block->escapeHtml($height) ?>" controls autoplay loop muted playsinline>
                                      <source src="<?=  $block->escapeUrl($block->getBaseUrl() .'media/' . $block->getImageVideoPoster($item)) ?>" type="video/mp4">
                                    </video>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php else: ?>
                        <?php if($item->getLink() && !empty($item->getDisplayLink())):?>
                            <a href="<?= $block->escapeUrl($item->getLink());?>" title="<?= $block->escapeHtmlAttr($item->getTitle());?>" class="data-link">
                                <img class="visible-md" width="100%" height="100%" src="<?= $block->escapeUrl($block->getImageDesktopUrl($item));?>" alt="<?= $block->escapeHtmlAttr($item->getTitle());?>" title="<?= $block->escapeHtmlAttr($item->getTitle());?>">
                                <img class="visible-xs" width="100%" height="100%" src="<?= $block->escapeUrl($block->getImageMobileUrl($item) ?: $block->getImageDesktopUrl($item));?>" alt="<?= $block->escapeHtmlAttr($item->getTitle());?>" title="<?= $block->escapeHtmlAttr($item->getTitle());?>">
                            </a>
                        <?php else: ?>
                            <div class="data-link">
                                <img class="visible-md" width="100%" height="100%" src="<?= $block->escapeUrl($block->getImageDesktopUrl($item));?>" alt="<?= $block->escapeHtmlAttr($item->getTitle());?>" title="<?= $block->escapeHtmlAttr($item->getTitle());?>">
                                <img class="visible-xs" width="100%" height="100%" src="<?= $block->escapeUrl($block->getImageMobileUrl($item) ?: $block->getImageDesktopUrl($item));?>" alt="<?= $block->escapeHtmlAttr($item->getTitle());?>" title="<?= $block->escapeHtmlAttr($item->getTitle());?>">
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                    <script type="text/x-magento-init">
                    {
                        "#<?= $block->escapeHtmlAttr($elementId) ?> .banner-item-<?= /** @noEscape  */ $item->getId(); ?>": {
                            "removeBanner": {
                                "endDate": "<?= /** @noEscape  */ $item->getEndDate(); ?>",
                                "itemId": "<?= /** @noEscape  */ $item->getId(); ?>",
                                "elementId":"<?= $block->escapeHtmlAttr($elementId) ?>"
                            }
                        }
                    }
                    </script>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
