<?php
/**
 * @var \Amasty\Storelocator\Block\View\Schedule $block
 * @var \Amasty\Storelocator\Model\Location $location
 */
$location = $block->getLocation();
$workToday = $location->getWorkingTimeToday();
?>

<div class="amlocator-schedule-container">
    <div class="amlocator-today"  data-amlocator-js="collapse-trigger">
        <strong><?= $block->escapeHtml(__('Open Time Today | ')); ?></strong>
        <span><strong><?= $block->escapeHtml($workToday); ?> <?= $block->escapeHtml(__('(Includes Sunday and holidays)')) ?></strong></span>
    </div>

    <div class="amlocator-week" data-amlocator-js="collapse-content" id="schedule<?= (int)$location->getId(); ?>">
        <div class="amlocator-schedule-table">
            <?php foreach ($location->dayNames as $key => $item) {
                $workingTime = $location->getWorkingTime($key);
                ?>
                <div class="amlocator-row">
                    <?php foreach ($workingTime as $keyTime => $time) { ?>
                        <span class="amlocator-cell -day"><?= $block->escapeHtml(__($keyTime)) ?></span>
                        <span class="amlocator-cell -time"><?= $block->escapeHtml(__($time)) ?></span>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
