<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */
/* @var $escaper \Magento\Framework\Escaper */
?>
<?php $_product = $block->getProduct() ?>
<?php $helper = $this->Helper(\Ecommage\ViewProduct\Helper\Data::class); //@codingStandardsIgnoreLine ?>
<?php
$helperCatalog = $this->helper(\Ecommage\CustomCatalog\Helper\Data::class); // @codingStandardsIgnoreLine
$qtyAndStock = $helperCatalog->checkQtyAndStockOptionProduct($_product);
$label = $helper->getLabelProductPage($_product);
?>
<?php if ($block->displayProductStockStatus()) : ?>
    <?php if ($_product->isAvailable() && $qtyAndStock) : ?>
        <p class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability:')) ?>">
            <span><?= $block->escapeHtml(__('In stock')) ?></span>
        </p>
    <?php elseif (!$_product->isAvailable()):?>
        <p class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability:')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
        </p>
    <?php elseif (!$qtyAndStock) :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Contact Price')) ?>">
            <span><?= $block->escapeHtml(__('Contact Price')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
<?php if($label): ?>
    <div class="amlabel-wrapper">
        <div class="amlabel-item">
            <?= /* @noEscape */ $label;?>
        </div>
    </div>
<?php endif; ?>

<?= $block->getChildHtml('bundle_prices') ?>
