<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_JetTheme
 */
?>
<?php
/**
 * @var $block Magento\Catalog\Block\Product\View
 * @var $escaper Magento\Framework\Escaper
 */
$_product = $block->getProduct();
$buttonTitle = __('Add to Cart');
$helper = $this->helper(\Ecommage\CustomCatalog\Helper\Data::class); // @codingStandardsIgnoreLine
$qtyAndStock = $helper->checkQtyAndStockOptionProduct($_product);
?>

<?php if ($_product->isSaleable() && $qtyAndStock):?>
    <div class="box-tocart">
        <div class="fieldset">
            <div class="actions">
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
