<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox$block */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$precentHelper = $this->helper('Ecommage\CustomCatalog\Helper\Data');
$text = __('As low as');
$specialLabel = __('Special Price');
$currentPage = $block->getRequest()->getFullActionName();
?>
<span class="normal-price">
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'display_label' => $text,
        'price_id' => $block->getPriceId('product-price-' . $idSuffix),
        'price_type' => 'finalPrice',
        'include_container' => true,
        'schema' => $schema,
    ]);?>
    <?php if($block->hasSpecialPrice()): ?>
    <?php if ($precentHelper->isPercentConfigurationProduct()) : ?>
        <?php $precentDiscount = $precentHelper->getPercentDiscountPrice($finalPriceModel->getAmount()->getValue(), $priceModel->getAmount()->getValue()) ?>
        <p class="percent-discount special-price"><?= $block->escapeHtml('(-' . $precentDiscount . '%)') ?></p>
    <?php endif; ?>
    <?php endif; ?>
</span>

<?php if (!$block->isProductList() && $block->hasSpecialPrice()) : ?>
    <span class="old-price sly-old-price no-display">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php endif; ?>

<?php if ($block->showMinimalPrice()) : ?>
    <?php if ($block->getUseLinkForAsLowAs()) :?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else :?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>
<?php if($currentPage == 'catalog_product_view' && $block->hasSpecialPrice()): ?>
    <script>
        require(['jquery','jquery/ui','mage/translate'],function($){
            $('.product-info-main .normal-price .price-label,.product-info-main .special-price .price-label').text('<?= $specialLabel; ?>');
        })
    </script>
<?php endif; ?>
