<div class="page-main-actions">
    <div class="page-actions">
        <div class="page-actions-buttons">
            <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                <div class="page-actions-inner" data-title="Import">
                    <div class="page-actions-buttons">
                        <button
                            id="back"
                            title="Back"
                            type="button"
                            onclick="window.history.back();"
                            class="action-scalable back">
                                <span><?= /* @noEscape */
                                    __('Back') ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
