<?php

/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_JetTheme
 */
?>
<?php
/**
 * @var $block Magento\Catalog\Block\Product\ListProduct
 * @var $ajaxViewModel Amasty\JetTheme\ViewModel\Catalog\Ajax
 * @var $layoutViewModel Amasty\JetTheme\ViewModel\CategoryPage\CategoryPageViewModel
 * @var $escaper Magento\Framework\Escaper
 */
// phpcs:disable
$brandHelper = $this->helper(\Amasty\ShopbyBase\Helper\OptionSetting::class);
$catalogHelper = $this->helper(\Ecommage\CustomCatalog\Helper\Data::class);
$storeID = $catalogHelper->getStoreId();

// phpcs:enable
use Magento\Framework\App\Action\Action;

$ajaxViewModel = $block->getAjaxViewModel();
$layoutViewModel = $block->getLayoutViewModel();
$_productCollection = $block->getLoadedProductCollection();
$_productNameType = $layoutViewModel->getProductDisplayNameType();
$_addToCartDisplay = $layoutViewModel->getDisplayAddToCartButton();
$_swatchDisplayType = $layoutViewModel->getSwatchDisplayType();
$_toShowProductItemInner = $_addToCartDisplay === 'hover' || ($_addToCartDisplay != 'always' && $_swatchDisplayType === 'hover');
// phpcs:ignore
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_mobileProductColumns = $layoutViewModel->getProductsPerLineMobile();
$_desktopProductColumns = $layoutViewModel->getProductsPerLineDesktop();
$buttonDetail = __('Detail');

?>

<?php if (!$_productCollection->count()) : ?>
<div class="message info empty">
    <span><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></span>
</div>
<?php else : ?>
<div class="top-toolbar">
    <?= $block->getToolbarHtml() ?>
</div>
<?= $block->getAdditionalHtml() ?>
<?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    }

    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $_products = $_productCollection->getItems();
    $params = $block->getRequest()->getParams();
    if (count($params) <= 1) {
        $_products = array_values($_products);
        shuffle($_products);
    }
    ?>
<div
    class="products wrapper <?= $escaper->escapeHtmlAttr($viewMode) ?> products-<?= $escaper->escapeHtmlAttr($viewMode) ?>">
    <ol
        class="products list items product-items -col-xl-<?= $escaper->escapeHtmlAttr($_desktopProductColumns) ?> -col-sm-<?= $escaper->escapeHtmlAttr($_mobileProductColumns) ?> -amtheme-buttons-<?= $escaper->escapeHtmlAttr($_addToCartDisplay) ?>  -amtheme-swatches-<?= $escaper->escapeHtmlAttr($_swatchDisplayType) ?>">
        <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
        <?php foreach ($_products as $_product) : ?>
        <li class="item product product-item">
            <div class="product-item-info" data-amtheme-js="product"
                data-container="product-<?= $escaper->escapeHtmlAttr($viewMode) ?>">
                <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        $qtyAndStock = $catalogHelper->checkQtyAndStockOptionProduct($_product);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }

                        $_productName = $escaper->escapeHtml($_helper->productAttribute($_product, $_product->getName(), 'name'));
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                <?php // Product Image
                        ?>
                <div class="product-photo-wrapper">
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                        class="product photo product-item-photo"
                        aria-label="<?= $escaper->escapeHtmlAttr($_productName) ?>" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                    <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                    <?php endif; ?>
                </div>
                <div class="product details product-item-details">
                    <h4 class="product name product-item-name -<?= $escaper->escapeHtmlAttr($_productNameType) ?>">
                        <a class="product-item-link" title="<?= $escaper->escapeHtmlAttr($_productName) ?>"
                            aria-label="<?= $escaper->escapeHtmlAttr($_productName) ?>"
                            href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                            <?= $escaper->escapeHtml($_productName) ?>
                        </a>
                    </h4>
                    <?php if ($layoutViewModel->getShowProductReviews()) : ?>
                    <?= $block->getReviewsSummaryHtml($_product, $templateType, true) ?>
                    <?php endif; ?>
                    <?php if ($layoutViewModel->getShowShortDescription() && $_product->getShortDescription()) : ?>
                    <div class="product-item-description am-custom-scrollbar">
                        <?= /* @noEscape */
                                    $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                    </div>
                    <?php endif; ?>
                    <?php if ($viewMode !== 'list') : ?>
                    <?php if (!$qtyAndStock || !$_product->isSalable()) : ?>
                    <div class="product-contact">
                        <?= $block->escapeHtml(__('Contact Price')); ?>
                    </div>
                    <?php else : ?>
                    <?= /* @noEscape */
                                    $block->getProductPrice($_product); ?>
                    <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($viewMode === 'list' || $_swatchDisplayType === 'always') : ?>
                    <?= $block->getProductDetailsHtml($_product) ?>
                    <?php endif; ?>
                </div>
                <?php if (($viewMode === 'grid' && $_toShowProductItemInner) || $viewMode === 'list') : ?>
                <div class="product-item-inner">
                    <?php endif; ?>
                    <?php if ($viewMode === 'list') : ?>
                    <?php if (!$qtyAndStock || !$_product->isSalable()) : ?>
                    <div class="product-contact">
                        <?= $block->escapeHtml(__('Contact Price')); ?>
                    </div>
                    <?php else : ?>
                    <?= /* @noEscape */
                                    $block->getProductPrice($_product); ?>
                    <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($viewMode !== 'list' && $_swatchDisplayType === 'hover') : ?>
                    <?= $block->getProductDetailsHtml($_product) ?>
                    <?php endif; ?>
                    <div class="product actions product-item-actions">
                        <?php if ($_product->isSaleable()) : ?>
                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                        <form data-role="tocart-form"
                            id="product_add_tocart_form<?= $escaper->escapeHtmlAttr($_product->getId()) ?>"
                            data-product-sku="<?= $escaper->escapeHtmlAttr($_product->getSku()) ?>"
                            action="<?= isset($postParams['action']) ? $escaper->escapeUrl($postParams['action']) : $escaper->escapeUrl($block->getAddToCartUrl($_product)) ?>"
                            method="post">
                            <input type="hidden" name="product"
                                value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                            <input type="hidden" name="<?= /* @noEscape */
                                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                value="<?= /* @noEscape */
                                                                                                                $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                            <?= $block->getBlockHtml('formkey') ?>
                            <button type="submit" title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                class="action tocart primary">
                                <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                            </button>
                            <?php $buttonTitle = __('Add to Cart'); ?>
                            <?php if (!$qtyAndStock) : ?>
                            <button type="button" title="<?= $block->escapeHtmlAttr($buttonDetail); ?>"
                                class="action primary buynow">
                                <span class="product contact product-item-contact">
                                    <a title="<?= $block->escapeHtmlAttr($buttonDetail); ?>"
                                        href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                                        class="product-item-link">
                                        <?= $block->escapeHtmlAttr($buttonDetail); ?>
                                    </a>
                                </span>
                            </button>
                            <?php else : ?>
                                <button type="submit"
                                        title="<?= $escaper->escapeHtmlAttr(__($buttonTitle)) ?>"
                                        class="action primary buynow">
                                    <span><?= $escaper->escapeHtml(__($buttonTitle)) ?></span>
                                </button>
                            <?php endif; ?>
                        </form>
                        <?php else : ?>
                        <?php if ($_product->isAvailable()) : ?>
                        <div class="stock available"><?= $escaper->escapeHtml(__('In stock')) ?></div>
                        <?php elseif (!$qtyAndStock) : ?>
                        <button type="button" title="<?= $block->escapeHtmlAttr($buttonDetail); ?>"
                            class="action primary buynow">
                            <span class="product contact product-item-contact">
                                <a title="<?= $block->escapeHtmlAttr($buttonDetail); ?>"
                                    href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                                    class="product-item-link">
                                    <?= $block->escapeHtmlAttr($buttonDetail); ?>
                                </a>
                            </span>
                        </button>
                        <?php else : ?>
                        <button type="button" title="<?= $block->escapeHtmlAttr($buttonDetail); ?>"
                            class="action primary buynow">
                            <span class="product contact product-item-contact">
                                <a title="<?= $block->escapeHtmlAttr($buttonDetail); ?>"
                                    href="<?= $block->escapeUrl($block->getProductUrl($_product)) ?>"
                                    class="product-item-link">
                                    <?= $block->escapeHtmlAttr($buttonDetail); ?>
                                </a>
                            </span>
                        </button>
                        <?php endif; ?>
                        <?php endif; ?>
                    </div>
                    <?php if (($viewMode === 'grid' && $_toShowProductItemInner) || $viewMode === 'list') : ?>
                </div>
                <?php endif; ?>
            </div>
        </li>
        <?php endforeach; ?>
    </ol>
</div>
<?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>

