<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */

$helper = $this->helper('Ecommage\Sms\Helper\Data'); //@codingStandardsIgnoreLine
?>


<script type="text/x-magento-init">
{
    "*": {
        "Sparsh_MobileNumberLogin/js/mobile-number": {}
    }
}
</script>
<div class="block block-customer-login">
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form password forget"
              action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                    <div class="field choice sparsh-mobile-number-login-option">
                        <label class="label sparsh-email-user active" for="email_user">
                            <input type="radio" name="user_option" class="radio" id="email_user" value="sparsh-email" checked="checked">
                            <span><?= $block->escapeHtml(__('Email')) ?></span>
                        </label>
                        <label class="label" for="mobile_number_user">
                            <input type="radio" name="user_option" class="radio" id="mobile_number_user" value="sparsh-mobile-number">
                            <span><?= $block->escapeHtml(__('Mobile Number')) ?></span>
                        </label>
                        <div class="custom-border"></div>
                    </div>
                    <div class="field sparsh-user-name sparsh-email required">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                        </div>
                    </div>
                <div class="field sparsh-user-name sparsh-mobile-number required">
                    <label class="label" for="mobile_number"><span><?= $block->escapeHtml(__('Mobile Number')) ?></span></label>
                    <div class="control">
                        <input type="number" name="login[username]" class="mobile_number"  autocomplete="off" class="input-text"  title="<?= $block->escapeHtmlAttr(__('Mobile Number')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-digits':true,'validate-phone-number':'true'}">
                    </div>
                </div>
                <input type="hidden" name="country_code">
                <?= $block->getChildHtml('form_additional_info') ?>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
                </div>
                <div class="secondary">
                    <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    window.isEnable = "<?= $block->escapeHtml($helper->isEnable()); ?>",
    window.urlResetPassword = "<?= $block->escapeHtml($helper->getUrlResetPassword()); ?>",
    window.urlForgotPass = "<?= $block->escapeUrl($helper->getUrlForgotPass()); ?>",
    window.loginUrl = "<?= $block->escapeUrl($block->getLoginUrl()) ?>"
</script>
