<?php
/**
 * Product list template
 *
 * @var $block \Ecommage\Recommendation\Block\ProductList\Recommendation
 * @var \Magento\Framework\Escaper $escaper
 * @var \Ecommage\Recommendation\Helper\Data $helper
 * @var \Ecommage\CustomCatalog\Helper\Data $helperCatalog

 */
?>

<?php
$helper = $this->helper('Ecommage\Recommendation\Helper\Data'); // @codingStandardsIgnoreLine
$helperCatalog = $this->helper('Ecommage\CustomCatalog\Helper\Data');// @codingStandardsIgnoreLine
$num = $helper->numProductList();
$scenarioIdRecommendedForYou = $helper->scenariaIdRecommendedForYou();
$scenarioIdSimilarRecently = $helper->scenariaIdSimilarRecently();
$url = $helper->urlRecommendationProductList();
$product = $block->getProduct();
$collections = $block->getCollection();
$flag = $block->getFlag();
$title = $helper->getTitle() ?: '';
$typeRecommendation = $block::RECOMMENDATION_FOR_YOU;
$typeSimilar = $block::SIMILAR_RECENTLY;
?>
<?php if($collections): ?>
        <div class="recommendation-slider block">
            <div class="block-title title title__wrapper" title="<?= $escaper->escapeHtmlAttr($title) ?>">
             <span class="text_line">
                 <?= $block->escapeHtml($title) ?>
             </span>
            </div>
            <div class="swiper-container product-items" id="<?= $block->escapeHtml($block->getCacheKey()) ?>">
                <div class="swiper-wrapper">
                    <?php foreach ($collections as $product) : ?>
                        <div class="swiper-slide">
                            <div class="item product product-item">
                                <div data-container="product-grid" class="product-item-info">
                                    <a tabindex="-1" class="product photo product-item-photo" href="<?= $block->escapeUrl($helper->getProductUrl($product->getId(),$block->getProductUrl($product))) ?>">
                                        <?= $block->getImage($product, 'category_page_list')->toHtml() ?>
                                    </a>
                                    <div class="product details product-item-details">
                                        <strong class="product name product-item-name">
                                            <a href="<?= $block->escapeUrl($helper->getProductUrl($product->getId(),$block->getProductUrl($product))) ?>" class="product-item-link">
                                                <?= $block->escapeHtml($product->getName()) ?>
                                            </a>
                                        </strong>
                                        <?php
                                        $qtyAndStock = $helperCatalog->checkQtyAndStockOptionProduct($product);
                                        ?>
                                        <?php if(!$qtyAndStock || !$product->isSalable()): ?>
                                            <div class="product-contact">
                                                <?= $block->escapeHtml(__('Contact Price')); ?>
                                            </div>
                                        <?php else: ?>
                                            <div class="product-price">
                                                <?= /* @noEscape */ $block->getProductPrice($product) ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <!-- Add Arrows -->
                <div class="swiper-button-next-<?= $block->escapeHtml($block->getCacheKey()) ?>"></div>
                <div class="swiper-button-prev-<?= $block->escapeHtml($block->getCacheKey()) ?>"></div>
            </div>
        </div>

    <script type="text/x-magento-init">
    {
        "#maincontent": {
            "recommendationSlider": {
                "cacheKey": "<?= $block->escapeHtml($block->getCacheKey()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>
<?php if($flag): ?>
    <div class="recommendation-recommended-for-you products products-grid"></div>
    <div class="recommendation-similar-recently products products-grid"></div>
    <script type="text/x-magento-init">
    {
        "#maincontent": {
            "recommendationProductList": {
                "num": "<?= $escaper->escapeHtml($num); ?>",
                "scenarioIdRecommendedForYou": "<?= $escaper->escapeHtml($scenarioIdRecommendedForYou) ?>",
                "scenarioIdSimilarRecently": "<?= $escaper->escapeHtml($scenarioIdSimilarRecently) ?>",
                "url": "<?= $escaper->escapeUrl($url) ?>",
                "typeRecommendation": "<?= $escaper->escapeHtml($typeRecommendation) ?>",
                "typeSimilar": "<?= $escaper->escapeHtml($typeSimilar) ?>"
            }
        }
    }
</script>
<?php endif; ?>

