<?php

/** @var RecentlyViewProduct $block */
$products = $block->createCollection();
if (!count($products)) {
    return;
}
$show_buttons  = explode(',', $block->getData('show_buttons'));
$showAddToCart = in_array('add_to_cart', $show_buttons) ? true : false;
$showWishlist  = in_array('add_to_wishlist', $show_buttons) ? true : false;
$showCompare   = in_array('add_to_compare', $show_buttons) ? true : false;
/** @codingStandardsIgnoreStart */
/** @var Image $_imageHelper */
$_imageHelper   = $this->helper('Magento\Catalog\Helper\Image');
$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
$compareHelper  = $this->helper('Magento\Catalog\Helper\Product\Compare');
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');

/** @codingStandardsIgnoreEnd */

use Magento\Catalog\Helper\Image;
use NiceForNow\RecentlyProduct\Block\RecentlyViewProduct;

?>


<div class="recently-view-product-slider">
    <div class="content-heading">
        <h2 class="title"><strong><?= $block->escapeHtml(__($block->getTitle())) ?></strong></h2>
    </div>
    <div class="block-clear-all">
        <a href="<?= $block->escapeUrl($block->getUrl('widget/clear/history')) ?>" class="clear-url-block">
            <strong><?= $block->escapeHtml(__('Clear history')) ?></strong>
        </a>
    </div>
    <div class="swiper-container" id="swiper_container_recently_view_products">
        <div class="swiper-wrapper">
            <?php foreach ($products as $product) : ?>
                <div class="swiper-slide">
                    <?php
                    $productImage = $_imageHelper->init($product, 'category_page_list')->constrainOnly(false)->keepAspectRatio(true)->keepFrame(false)->resize(400)->getUrl();
                    $productUrl   = $product->getUrlModel()->getUrl($product);
                    ?>
                    <div class="item product product-item">
                        <div data-container="product-grid" class="product-item-info">
                            <a tabindex="-1" class="product photo product-item-photo" href="<?= /* @noEscape */
                            $productUrl; ?>">
                                <span style="width:240px;" class="product-image-container">
                                    <span style="padding-bottom: 125%;" class="product-image-wrapper">
                                        <img width="240" height="300"
                                             alt="<?= /* @noEscape */
                                             $product->getName(); ?>"
                                             src="<?= /* @noEscape */
                                             $productImage; ?>"
                                             class="product-image-photo"
                                        />
                                    </span>
                                </span>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name">
                                    <a href="<?= /* @noEscape */
                                    $productUrl; ?>" class="product-item-link">
                                        <?= /* @noEscape */
                                        $product->getName(); ?>
                                    </a>
                                </strong>
                                <?= /* @noEscape */
                                $block->getProductPrice($product); ?>
                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <?php if ($showAddToCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($product->isSaleable()): ?>
                                                    <?php if ($product->getTypeInstance()->hasRequiredOptions($product)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?= /* @noEscape */
                                                                $block->getAddToCartUrl($product) ?>"}}' type="button"
                                                                title="<?= /* @noEscape */ __('View More') ?>">
                                                            <span><?= /* @noEscape */ __('View More') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($product), ['product' => $product->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= /* @noEscape */
                                                                $postData; ?>'
                                                                type="button" title="<?= /* @noEscape */
                                                        __('Add to Cart') ?>">
                                                            <span><?= /* @noEscape */
                                                                __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($product->getIsSalable()): ?>
                                                        <div class="stock available"><span><?= /* @noEscape */
                                                                __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= /* @noEscape */
                                                                __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>

                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="secondary-addto-links actions-secondary"
                                                     data-role="add-to-links">

                                                    <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
                                                        <a href="#" data-post='<?= /* @noEscape */
                                                        $block->getAddToWishlistParams($product); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?= /* @noEscape */
                                                           __('Add to Wish List') ?>">
                                                            <span><?= /* @noEscape */
                                                                __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>

                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?= /* @noEscape */
                                                           $compareHelper->getPostDataParams($product); ?>'
                                                           data-role="add-to-links"
                                                           title="<?= /* @noEscape */
                                                           __('Add to Compare'); ?>">
                                                            <span><?= /* @noEscape */
                                                                __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <!-- Add Arrows -->
        <div class="swiper-button-next-recently swiper-button-black"></div>
        <div class="swiper-button-prev-recently swiper-button-black"></div>
    </div>
</div>
<script>
    require(['jquery', 'swiper94now'], function ($, Swiper) {
        jQuery(document).ready(function () {
            var swiper = new Swiper('#swiper_container_recently_view_products', {
                slidesPerView: 3,
                spaceBetween: 30,
                effect: 'fadeOut',
                autoplay: {
                    delay: 5000,
                    disableOnInteraction: true,
                },
                pagination: {
                    clickable: true,
                },
                navigation: {
                    nextEl: '.swiper-button-next-recently',
                    prevEl: '.swiper-button-prev-recently',
                },
                breakpoints: {
                    640: {
                        slidesPerView: 3,
                        spaceBetween: 10,
                    },
                    767: {
                        slidesPerView: 3,
                        spaceBetween: 10,
                    },
                    1024: {
                        slidesPerView: 3,
                        spaceBetween: 10,
                    },
                    1279: {
                        slidesPerView: 5,
                        spaceBetween: 20,
                    },
                }
            });
        });
    });
</script>
