<?php

/** @var RecentlyViewProduct $block */
$items = $block->createCollection();
if (!count($items)) {
    return;
}
$show_buttons  = explode(',', $block->getData('show_buttons'));
$showAddToCart = in_array('add_to_cart', $show_buttons) ? true : false;
$showWishlist  = in_array('add_to_wishlist', $show_buttons) ? true : false;
$showCompare   = in_array('add_to_compare', $show_buttons) ? true : false;
/** @codingStandardsIgnoreStart */
/** @var Image $_imageHelper */
$_imageHelper   = $this->helper('Magento\Catalog\Helper\Image');
$postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
$compareHelper  = $this->helper('Magento\Catalog\Helper\Product\Compare');
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
$type = 'widget-product-grid';
$mode = 'grid';
$image = 'new_products_content_widget_grid';
$description = false;
/** @codingStandardsIgnoreEnd */
use Magento\Catalog\Helper\Image;
use NiceForNow\RecentlyProduct\Block\RecentlyViewProduct;
?>

<div class="block widget block-products-list <?= /* @noEscape */ $mode ?>">
    <?php if ($block->getTitle()) : ?>
        <div class="block-title title__wrapper title__center">
            <span class="text_line"><?= $block->escapeHtml(__($block->getTitle())) ?></span>
            <a href="<?= $block->escapeUrl($block->getUrl('widget/clear/history')) ?>" class="clear-url-block">
                <strong><?= $block->escapeHtml(__('Clear history')) ?></strong>
            </a>
        </div>
    <?php endif ?>
    <div class="block-content">
        <?= /* @noEscape */ '<!-- ' . $image . '-->' ?>
        <div class="products-<?= /* @noEscape */ $mode ?> <?= /* @noEscape */ $mode ?>">
            <ol class="product-items <?= /* @noEscape */ $type ?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item) : ?>
                    <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                    <div class="product-item-info">
                        <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                            <?= $block->getImage($_item, $image)->toHtml() ?>
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <a title="<?= $block->escapeHtmlAttr($_item->getName()) ?>"
                                   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>
                            <?= /* @noEscape */
                            $block->getProductPrice($_item); ?>

                            <?php if ($showWishlist || $showCompare || $showAddToCart) : ?>
                                <div class="product-item-inner">
                                    <div class="product-item-actions">
                                        <?php if ($showAddToCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?= /* @noEscape */
                                                            $postData; ?>'
                                                            type="button" title="<?= /* @noEscape */
                                                    __('Add to Cart') ?>">
                                                        <span><?= /* @noEscape */
                                                            __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?= /* @noEscape */
                                                                __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?= /* @noEscape */
                                                                __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare) : ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <div class="secondary-addto-links actions-secondary"
                                                     data-role="add-to-links">

                                                    <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
                                                        <a href="#" data-post='<?= /* @noEscape */
                                                        $block->getAddToWishlistParams($_item); ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?= /* @noEscape */
                                                           __('Add to Wish List') ?>">
                                                            <span><?= /* @noEscape */
                                                                __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>

                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?= /* @noEscape */
                                                           $compareHelper->getPostDataParams($_item); ?>'
                                                           data-role="add-to-links"
                                                           title="<?= /* @noEscape */
                                                           __('Add to Compare'); ?>">
                                                            <span><?= /* @noEscape */
                                                                __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
