<?php /** @var $block \Magezon\TabsPro\Block\Tab */ ?>
<?php /** @var $escaper Magento\Framework\Escaper */ ?>
<?php
use Magento\Framework\App\Action\Action;
$coreHelper           = $this->helper('\Magezon\TabsPro\Helper\CoreData');
$items                = $block->getItems();
$count                = count($items);
$type                 = 'widget-product-grid';
$mode                 = 'grid';
$image                = 'new_products_content_widget_grid';
$title                = $block->getTitle() ? __($block->getTitle()) : '';
$showName             = $block->getData('product_name');
$showImage            = $block->getData('product_image');
$imageWidth           = (int) $block->getData('product_image_width');
$imageHeight          = (int) $block->getData('product_image_height');
$showPrice            = $block->getData('product_price');
$showShortDescription = $block->getData('product_shortdescription');
$showReview           = $block->getData('product_review');
$showWishlist         = $block->getData('product_wishlist');
$showCompare          = $block->getData('product_compare');
$showCart             = $block->getData('product_addtocart');
$templateType         = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$data                 = $block->getData();
$compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);
$helperCatalog      = $this->helper(\Ecommage\CustomCatalog\Helper\Data::class); // @codingStandardsIgnoreLine
$helperLabel      = $this->helper(\Ecommage\CustomAmastyLabel\Helper\Label::class); // @codingStandardsIgnoreLine
$wishlistHelper = $this->helper(\Magento\Wishlist\Helper\Data::class);
unset($data['items']);
$helperRec = $this->helper('Ecommage\Recommendation\Helper\Data');
$colection = [];
$column = 5;
$items_per_column = 1;
if ((int)$data['items_per_column']) {
    $items_per_column = $data['items_per_column'];
}
$dataHelper = $this->helper('\Ecommage\TabsPro\Helper\Data');
if ($dataHelper->isMobile() && !empty($data['items_per_column_mb'])) {
    $items_per_column = $data['items_per_column_mb'];
}
if($count%$items_per_column == 0){
    $column = $count/$items_per_column;
}else{
    $column = floor($count/$items_per_column)+1;
}
$i = $x = 0;
foreach ($items as $item) {
    if($i<$column){
        $i++;
    }else{
        $i = 1;
        $x++;
    }
    $colection[$i][$x] = $item;
}
?>
<?php if ($count) { ?>
    <ul class="owl-carousel product-items tabspro-items"
        data-device-0="<?php echo $data['owl_device_0'] ?>"
        data-device-480="<?php echo $data['owl_device_480'] ?>"
        data-device-768="<?php echo $data['owl_device_768'] ?>"
        data-device-960="<?php echo $data['owl_device_960'] ?>"
        data-device-1024="<?php echo $data['owl_device_1024'] ?>"
        data-autoplay="<?php echo $data['owl_autoplay']?'true':'false' ?>"
        data-nav="<?php echo $data['owl_nav']?'true':'false' ?>"
        data-autoplay-hover-pause="<?php echo $data['owl_autoplay_hover_pause']?'true':'false' ?>"
        data-dots="<?php echo $data['owl_dots']?'true':'false' ?>"
        data-autoplay-timeout="<?php echo $data['owl_autoplay_timeout'] ?>"
        data-lazyload="<?php echo $data['owl_lazyload']?'true':'false' ?>"
        data-loop="<?php echo $data['owl_loop']?'true':'false' ?>"
        data-rtl="<?php echo $data['owl_rtl']?'true':'false' ?>"
        data-margin="<?php echo $data['owl_margin'] ?>"
        data-mousedrag="<?php echo $data['owl_mousedrag']?'true':'false' ?>"
        data-touchdrag="<?php echo $data['owl_touchdrag']?'true':'false' ?>"
        data-pulldrag="<?php echo $data['owl_pulldrag']?'true':'false' ?>"
        data-parent-id="<?php echo $data['tab_id'] ?>"
    >
        <?php $iterator = 1; ?>


        <?php foreach ($colection as $_items): ?>
            <li class="item product-item <?php if (count($_items)>1) { echo 'multirow'; } ?>">
                <?php foreach ($_items as $_item): ?>
                    <div class="product-item-info">
                        <?php if ($showImage) { ?>
                            <div class="product-photo-wrapper">
                                <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?php
                                    $imageParams = [];
                                    if ($data['owl_lazyload']) {
                                        $imageParams['data-lazyload'] = 1;
                                    }
                                    $imgHtml = $block->getTabProductImage($data['owl_lazyload'], $_item, $image, $imageParams, $imageWidth, $imageHeight)->toHtml();
                                    if ($data['owl_lazyload']) {
                                        $imgHtml = str_replace('<img class="', '<img class="owl-lazy ', $imgHtml);
                                    }
                                    ?>
                                    <?= /* @noEscape */ $imgHtml ?>
                                    <?= /* @noEscape */ $helperLabel->renderProductLabel($_item) ?>
                                </a>
                                <div class="amtheme-icons-position -top-right">
                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div class="amtheme-icon-wrapper">
                                            <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>'
                                                   class="action towishlist amtheme-circle-icon"
                                                   title="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>"
                                                   aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wishlist')) ?>"
                                                   data-action="add-to-wishlist"
                                                   role="button">
                                                    <svg class="amtheme-icon -hover-bg">
                                                        <use xlink:href="#icon-wishlist" />
                                                    </svg>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <a href="#"
                                                   data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>'
                                                   class="action tocompare amtheme-circle-icon"
                                                   title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                   aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
                                                   data-action="add-to-compare"
                                                   role="button">
                                                    <svg class="amtheme-icon -hover-bg">
                                                        <use xlink:href="#icon-compare"/>
                                                    </svg>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="product details product-item-details">
                            <?php if ($showName): ?>
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                            <?php endif; ?>
                            <?php if ($showPrice): ?>
                                <?php $qtyAndStock = $helperCatalog->checkQtyAndStockOptionProduct($_item);?>
                                <?php if(!$qtyAndStock || !$_item->isSalable()): ?>
                                    <div class="product-contact">
                                        <?= $block->escapeHtml(__('Contact Price')); ?>
                                    </div>
                                <?php else: ?>
                                    <div class="product-details-action">
                                        <?php echo $block->getProductPriceHtml($_item, $type); ?>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                            <?php
                            if (isset($data['product_swatches']) && $data['product_swatches']):
                                echo $block->getSwatchHtml($_item, $data['tab_id']);
                            endif;
                            ?>

                            <?php if ($templateType && $showReview): ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if ($showShortDescription) { ?>
                                <p class="product-item-shortdescription"><?php echo $coreHelper->filter($_item->getShortDescription()) ?></p>
                            <?php } ?>

                            <?php if ($showWishlist || $showCompare || $showCart): ?>
                            <?php if ($showCart): ?>
                            <div class="product actions product-item-actions">
                                <?php if ($_item->isSaleable()): ?>
                                    <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                    <form data-role="tocart-form" data-product-sku="<?= $escaper->escapeHtml($_item->getSku()); ?>" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                        <?php if ($formKey = $block->getProductFormKey()) { ?>
                                            <input name="form_key" type="hidden" value="<?php echo $formKey ?>" />
                                        <?php } else { ?>
                                            <?php echo $block->getBlockHtml('formkey')?>
                                        <?php } ?>
                                        <button type="submit"
                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                class="action primary buynow">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                        </button>
                                    </form>
                                <?php else: ?>
                                    <button type="button" title="<?= $block->escapeHtmlAttr(__('Detail')); ?>"
                                            class="action primary buynow">
                                <span class="product contact product-item-contact">
                                    <a title="<?= $block->escapeHtmlAttr(__('Detail')); ?>"
                                       href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtmlAttr(__('Detail')); ?>
                                    </a>
                                </span>
                                    </button>
                                <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif; ?>
                    </div>
                <?php endforeach ?>
            </li>
        <?php endforeach ?>
    </ul>
<?php } ?>
