<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_JetTheme
 */
?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>

<div class="amtheme-backtotop-wrap" data-amtheme-js="backtotop-wrap" tabindex="0">
    <svg class="amtheme-icon">
        <use xlink:href="#icon-arrow-left"/>
    </svg>
    <div class="amtheme-label"><?= $block->escapeHtml(__('Back to Top')); ?></div>
</div>
